# Generated by Django 6.1 on 2026-08-08 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cal_url",
                    models.URLField(
                        max_length=2000, unique=True, verbose_name="calendar URL"
                    ),
                ),
                ("website_url", models.URLField(blank=True, max_length=2000)),
                ("is_active", models.BooleanField(default=True)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "source_format",
                    models.CharField(default="ics", editable=False, max_length=20),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_uid", models.CharField(max_length=255)),
                ("recurrence_id", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField()),
                ("is_all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("team1", models.CharField(blank=True, max_length=255)),
                ("team2", models.CharField(blank=True, max_length=255)),
                ("event_url", models.URLField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("tentative", "Tentative"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="pages.calendar",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("calendar", "external_uid", "recurrence_id"),
                        name="unique_calendar_event_instance",
                    )
                ],
            },
        ),
    ]
