# Generated by Django 6.1 on 2026-08-08 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("game", "Game"),
                    ("practice", "Practice"),
                    ("tournament", "Tournament"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CalendarEventRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "match_field",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("description", "Description"),
                            ("location", "Location"),
                            ("category", "ICS category"),
                        ],
                        default="title",
                        max_length=20,
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="Case-insensitive text to look for, such as ‘practice’.",
                        max_length=200,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("game", "Game"),
                            ("practice", "Practice"),
                            ("tournament", "Tournament"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100, help_text="Lower numbers are applied first."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_rules",
                        to="pages.calendar",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
            },
        ),
    ]
