# Generated by Django 6.1 on 2026-08-08 14:44

import re

from django.db import migrations


def classify_existing_events(apps, schema_editor):
    CalendarEvent = apps.get_model("pages", "CalendarEvent")
    for event in CalendarEvent.objects.all().iterator():
        categories = " ".join((event.raw_data or {}).get("categories", []))
        searchable = f"{event.title} {categories}".casefold()
        if re.search(r"\b(practice|training|workout)\b", searchable):
            event_type = "practice"
        elif re.search(r"\b(tournament|championship|playoffs?)\b", searchable):
            event_type = "tournament"
        elif re.search(r"\b(game|match|scrimmage)\b", searchable) or re.search(
            r"\s+(vs\.?|v\.?|@|at)\s+", event.title, re.IGNORECASE
        ):
            event_type = "game"
        else:
            event_type = "other"
        CalendarEvent.objects.filter(pk=event.pk).update(event_type=event_type)


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_calendarevent_event_type_calendareventrule"),
    ]

    operations = [migrations.RunPython(classify_existing_events, migrations.RunPython.noop)]
