# Generated by Django 6.1 on 2026-08-08 14:49

from django.db import migrations, models


def use_arizona_timezone(apps, schema_editor):
    Calendar = apps.get_model("pages", "Calendar")
    Calendar.objects.all().update(timezone="America/Phoenix")


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_classify_existing_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="timezone",
            field=models.CharField(default="America/Phoenix", max_length=64),
        ),
        migrations.RunPython(use_arizona_timezone, migrations.RunPython.noop),
    ]
