# Generated by Django 6.1 on 2026-08-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_geocodedlocation_routeestimate"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoapifyAPILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("geocoding", "Geocoding"), ("routing", "Routing")],
                        max_length=20,
                    ),
                ),
                ("method", models.CharField(default="GET", max_length=10)),
                ("endpoint", models.URLField(max_length=500)),
                ("request_params", models.JSONField(default=dict)),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.TextField(blank=True)),
                ("response_size_bytes", models.PositiveIntegerField(default=0)),
                ("response_truncated", models.BooleanField(default=False)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["request_type", "created_at"],
                        name="pages_geoap_request_de77a8_idx",
                    ),
                    models.Index(
                        fields=["success", "created_at"],
                        name="pages_geoap_success_92be43_idx",
                    ),
                ],
            },
        ),
    ]
