# Generated by Django 6.1 on 2026-08-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_geoapifyapilog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["url"],
            },
        ),
    ]
