# Generated by Django 6.1 on 2026-08-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_savedlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedlink",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
