# Generated by Django 6.1 on 2026-08-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_savedlink_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="is_mine",
            field=models.BooleanField(
                default=False, help_text="Treat every event from this calendar as mine."
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="team_aliases",
            field=models.TextField(
                blank=True,
                help_text="Team names from this feed that should count as mine, one per line.",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="is_mine",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
