# Generated by Django 6.1 on 2026-08-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_calendar_is_mine_calendar_team_aliases_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="is_visible",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name="CalendarVisibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "match_field",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("description", "Description"),
                            ("location", "Location"),
                            ("category", "ICS category"),
                            ("team", "Either team"),
                        ],
                        default="title",
                        max_length=20,
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="Case-insensitive text to look for, such as a team name.",
                        max_length=200,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("show", "Show only matches"),
                            ("hide", "Hide matches"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Lower numbers are displayed first. Hide always wins.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_rules",
                        to="pages.calendar",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
            },
        ),
    ]
