# Generated by Django 6.1 on 2026-09-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_calendarevent_is_visible_calendarvisibilityrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="source_filename",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="cal_url",
            field=models.URLField(
                blank=True,
                help_text="Optional for calendars imported from an uploaded ICS file.",
                max_length=2000,
                null=True,
                unique=True,
                verbose_name="calendar URL",
            ),
        ),
    ]
