# Generated by Django 6.1 on 2026-09-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_calendar_source_filename_alter_calendar_cal_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedlink",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
