# Generated by Django 6.1 on 2026-09-19 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_savedlink_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="source_ends_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="source_is_all_day",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="source_starts_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="EventTimeOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_uid", models.CharField(max_length=255)),
                ("recurrence_id", models.CharField(blank=True, max_length=255)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("is_all_day", models.BooleanField(default=False)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_overrides",
                        to="pages.calendar",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("calendar", "external_uid", "recurrence_id"),
                        name="unique_event_time_override",
                    )
                ],
            },
        ),
    ]
