# Generated by Django 6.1 on 2026-09-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_calendarevent_source_ends_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="is_manual",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
