# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_calendarevent_is_manual"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDetailsOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_uid", models.CharField(max_length=255)),
                ("recurrence_id", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("address", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("tentative", "Tentative"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_overrides",
                        to="pages.calendar",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("calendar", "external_uid", "recurrence_id"),
                        name="unique_event_details_override",
                    )
                ],
            },
        ),
    ]
